In [1]:
import numpy as np

# Array

In [23]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [3]:
np.array([1, 2, 3, 4.5])

array([1. , 2. , 3. , 4.5])

In [4]:
np.array([1, 2, 3, 4.5, 5.5, 6.5, '7'])

array(['1', '2', '3', '4.5', '5.5', '6.5', '7'], dtype='<U32')

In [6]:
arr

array([1, 2, 3, 4, 5, 6])

In [7]:
arr[0]

1

In [8]:
arr[1:4]

array([2, 3, 4])

In [9]:
np.array([1, 2, 3, 4, 5], dtype=float)

array([1., 2., 3., 4., 5.])

In [13]:
arr = np.array([1, 2, 3, 4, 5], ndmin=10)

In [14]:
arr.ndim

10

In [21]:
l = [1, 2, 3, 4, 5, 6]
arr = np.array(l)
arr

array([1, 2, 3, 4, 5, 6])

In [16]:
lst_conv_arr = np.asarray(l)
lst_conv_arr

array([1, 2, 3, 4, 5, 6])

In [17]:
arr.cumsum()

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

In [24]:
arr.argmax()

5

In [19]:
arr.argmin()

0

In [20]:
arr.dtype

dtype('int32')

In [25]:
arr.max()

6

In [26]:
arr.min()

1

In [30]:
arr = np.arange(0, 100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [34]:
arr.reshape(20, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [36]:
arr.resize(10, 10)

In [37]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

# From Function

In [38]:
np.fromfunction(lambda i, j: i+j, (5, 5))

array([[0., 1., 2., 3., 4.],
       [1., 2., 3., 4., 5.],
       [2., 3., 4., 5., 6.],
       [3., 4., 5., 6., 7.],
       [4., 5., 6., 7., 8.]])

In [39]:
np.fromfunction(lambda i, j: i*j, (5, 5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  2.,  4.,  6.,  8.],
       [ 0.,  3.,  6.,  9., 12.],
       [ 0.,  4.,  8., 12., 16.]])

In [40]:
def func(i, j):
    return i*j

In [41]:
f = func

In [48]:
np.fromfunction(lambda i, j: i==j, (5, 5))

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

In [50]:
l = [i for i in range(10)]
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [52]:
np.fromiter(l, float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [54]:
np.fromstring("10,20,30,40,50", sep=",", dtype=int)

array([10, 20, 30, 40, 50])

# Zeros and Ones

In [57]:
np.zeros(20, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [59]:
arr_z = np.zeros(20, dtype=int)

In [66]:
for i in range(20):
    print(arr_z+i)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
[4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4]
[5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9]
[10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10]
[11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11]
[12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12]
[13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13]
[14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14]
[15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15]
[16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16]
[17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17]
[18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18]
[19 19 19 19 19 19 19 

In [67]:
i = 1
for j in arr_z:
    print(j+i)
    i+=1

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [69]:
np.ones(100, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [71]:
np.linspace(1, 5, 7)

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        ])

In [75]:
np.ones((2, 2, 10))

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

# Random

In [76]:
np.random.rand(10)

array([0.45079294, 0.87457805, 0.69673094, 0.26851877, 0.20392243,
       0.85365364, 0.71621279, 0.88119425, 0.74418192, 0.92593994])

In [77]:
np.random.rand(4, 4)

array([[0.94053217, 0.41616148, 0.17336823, 0.18938971],
       [0.18051069, 0.45642986, 0.30887446, 0.63736595],
       [0.87686656, 0.48155081, 0.04449348, 0.05491531],
       [0.64744524, 0.78044286, 0.53009824, 0.41594217]])

In [78]:
np.random.randn(5, 5)

array([[-0.79303233,  1.6441606 ,  0.01226736, -1.32912823, -1.7943361 ],
       [-0.52942083,  1.09649305, -0.76788344,  0.81472159, -0.13587324],
       [ 0.60160431,  1.57481692,  0.47139163, -0.43894679, -0.66442948],
       [ 1.03261921,  0.33536017, -0.67506956, -0.71230754,  0.07197298],
       [-0.67677207,  2.03405116, -0.40504065, -0.43883599,  0.05445412]])

In [90]:
np.random.randint(10, 100)

24

In [93]:
arr = np.random.randint(10, 100, (10, 10))
arr

array([[34, 90, 32, 24, 66, 79, 59, 71, 31, 30],
       [66, 54, 84, 96, 99, 73, 75, 12, 71, 90],
       [44, 73, 59, 20, 59, 30, 72, 74, 99, 32],
       [55, 42, 21, 12, 30, 39, 71, 90, 19, 66],
       [10, 77, 21, 14, 58, 92, 50, 49, 70, 60],
       [32, 20, 53, 67, 35, 68, 75, 69, 13, 89],
       [80, 21, 27, 99, 25, 58, 86, 83, 30, 81],
       [46, 64, 40, 61, 15, 41, 88, 50, 76, 37],
       [84, 33, 15, 12, 32, 44, 44, 97, 74, 23],
       [97, 74, 31, 25, 59, 87, 69, 35, 93, 66]])

# Stats and math

In [94]:
arr[0]

array([34, 90, 32, 24, 66, 79, 59, 71, 31, 30])

In [95]:
np.sin(arr[0])

array([ 0.52908269,  0.89399666,  0.55142668, -0.90557836, -0.02655115,
       -0.44411267,  0.63673801,  0.95105465, -0.40403765, -0.98803162])

In [96]:
np.cos(arr[0])

array([-0.84857027, -0.44807362,  0.83422336,  0.42417901, -0.99964746,
       -0.89597095, -0.77108022, -0.30902273,  0.91474236,  0.15425145])

In [97]:
np.tan(arr[0])

array([-0.62349896, -1.99520041,  0.66100604, -2.1348967 ,  0.02656052,
        0.49567753, -0.82577401, -3.0776204 , -0.44169557, -6.4053312 ])

In [98]:
np.pi

3.141592653589793

In [99]:
np.degrees(arr[0])

array([1948.05650344, 5156.62015618, 1833.46494442, 1375.09870831,
       3781.52144786, 4526.36658153, 3380.45099127, 4068.00034543,
       1776.16916491, 1718.87338539])

In [104]:
np.percentile(arr[0], 50, axis=0)

46.5

In [102]:
arr[0].mean()

51.6

In [106]:
np.median(arr[0])

46.5

In [107]:
arr[0]

array([34, 90, 32, 24, 66, 79, 59, 71, 31, 30])

In [109]:
np.sort(arr[0])

array([24, 30, 31, 32, 34, 59, 66, 71, 79, 90])

In [110]:
np.average(arr[0])

51.6

In [111]:
np.std(arr[0])

22.826300620118012

In [112]:
np.var(arr[0])

521.04

In [114]:
np.sqrt(arr[0])

array([5.83095189, 9.48683298, 5.65685425, 4.89897949, 8.1240384 ,
       8.88819442, 7.68114575, 8.42614977, 5.56776436, 5.47722558])